# config/packages/snc_redis.yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://:%env(REDIS_PASSWORD)%@%env(REDIS_SOCKET)%/0'
            logging: false
            options:
                connection_timeout: 10.0
                read_write_timeout: 30.0
                
        cache:
            type: predis
            alias: cache
            dsn: 'redis://:%env(REDIS_PASSWORD)%@%env(REDIS_SOCKET)%/1'
            logging: false
            options:
                connection_timeout: 10.0
                read_write_timeout: 30.0