# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    redis.socket_path: '/home2/divi4480/.cpanel/redis/redis.sock'
    redis.password: '%env(REDIS_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # Enregistrement explicite de UsersAuthenticator
    App\Security\UsersAuthenticator:
        arguments:
            $urlGenerator: '@router'
        tags:
            - { name: 'security.authenticator' }

    # Service de cache maintenance avec SncRedis (SANS constantes Redis)
    App\Service\MaintenanceCacheService:
        arguments:
            $redis: '@snc_redis.default'
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'maintenance_cache' }

    # Alias pour compatibilité
    maintenance.cache:
        alias: App\Service\MaintenanceCacheService
        public: true

    App\Service\KizeoCacheService:
        arguments:
            $cache: '@cache.app'
            $logger: '@monolog.logger.kizeo_cache'
        tags:
            - { name: 'monolog.logger', channel: 'kizeo_cache' }

    # Configuration du service ImageStorageService
    App\Service\ImageStorageService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $logger: '@logger'

    # Configuration du contrôleur avec injection des dépendances
    App\Controller\SimplifiedMaintenanceController:
        arguments:
            $imageStorageService: 'App\Service\ImageStorageService'
            $client: '@http_client'
            $logger: '@logger'

    # Configuration du repository avec injection du service
    App\Repository\FormRepository:
        arguments:
            $registry: '@doctrine'
            $client: '@http_client'
            $imageStorageService: '@App\Service\ImageStorageService'

   # Configuration de la commande
    App\Command\MigratePhotosCommand:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $formRepository: '@App\Repository\FormRepository'  # ✅ CORRIGÉ aussi
            $imageStorageService: '@App\Service\ImageStorageService'  # ✅ CORRIGÉ
        tags:
            - { name: 'console.command' }